Traceback (most recent call last):
  File "/Users/lexxx/ecu/get_dam.py", line 109, in <module>
    if not data_downloaded(day_ahead_date):
  File "/Users/lexxx/ecu/get_dam.py", line 19, in data_downloaded
    with open('status_log.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'status_log.txt'
Traceback (most recent call last):
  File "/Users/lexxx/ecu/get_dam.py", line 109, in <module>
    if not data_downloaded(day_ahead_date):
  File "/Users/lexxx/ecu/get_dam.py", line 19, in data_downloaded
    with open('status_log.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'status_log.txt'
Traceback (most recent call last):
  File "/Users/lexxx/ecu/get_dam.py", line 109, in <module>
    if not data_downloaded(day_ahead_date):
  File "/Users/lexxx/ecu/get_dam.py", line 19, in data_downloaded
    with open('status_log.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'status_log.txt'
Traceback (most recent call last):
  File "/Users/lexxx/ecu/get_dam.py", line 109, in <module>
    if not data_downloaded(day_ahead_date):
  File "/Users/lexxx/ecu/get_dam.py", line 19, in data_downloaded
    with open('status_log.txt', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'status_log.txt'
